app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

backend_user:
    resource: "@BackendUserBundle/Resources/config/routing.yml"
    prefix:   /api

rest_music_diff:
    resource: "@RestMusicDiffBundle/Resources/config/routing.yml"
    prefix:   /api
